FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install
# Copy source code (volume mount will override in dev)
COPY . .

# Expose the port your backend runs on
EXPOSE 5000

# Use nodemon for live reload in development
CMD ["npx", "nodemon", "server.js"]